name: RandomChestSpawn
version: '${version}'
main: fr.zwartkat.randomchestspawn.RandomChestSpawn
api-version: '1.20'
commands:
  rcs:
    description: 'RandomChestSpawn commands'
    permission: rsc.command
    permission-message: 'You are not allowed to use this command'
softdepend: [PlaceholderAPI]